### ISSUE TITLE
Octoblu/alljoyn installation failing in Ubuntu 14.04 and Raspberry 

### ISSUE THREAD

**Issue by kgan4dev** [octoblu/alljoyn#11]
In Linux, install command 

$ npm install alljoyn

got end with these error messages 

 CXX(target) Release/obj.target/node-alljoyn/src/bindings.o
../src/bindings.cc: In function ‘void init(v8::Handle<v8::Object>)’:
../src/bindings.cc:21:71: error: no matching function for call to ‘v8::FunctionTemplate::New(void (&)(const v8::FunctionCallbackInfo<v8::Value>&))’
   Local<Function> busWrap = FunctionTemplate::New(BusAttachmentWrapper)->GetFunction();
                                                                       ^
../src/bindings.cc:21:71: note: candidate is:
In file included from /home/user/.node-gyp/0.12.2/src/node.h:61:0,
                 from ../src/bindings.cc:1:
/home/user/.node-gyp/0.12.2/deps/v8/include/v8.h:3455:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/user/.node-gyp/0.12.2/deps/v8/include/v8.h:3455:34: note:   no known conversion for argument 1 from ‘void(const v8::FunctionCallbackInfo<v8::Value>&)’ to ‘v8::Isolate*’
../src/bindings.cc:23:84: error: no matching function for call to ‘v8::FunctionTemplate::New(void (&)(const v8::FunctionCallbackInfo<v8::Value>&))’
   Local<Function> interfaceWrap = FunctionTemplate::New(InterfaceDescriptionWrapper)->GetFunction();
                                                                                    ^
../src/bindings.cc:23:84: note: candidate is:
In file included from /home/user/.node-gyp/0.12.2/src/node.h:61:0,
                 from ../src/bindings.cc:1:
/home/user/.node-gyp/0.12.2/deps/v8/include/v8.h:3455:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/user/.node-gyp/0.12.2/deps/v8/include/v8.h:3455:34: note:   no known conversion for argument 1 from ‘void(const v8::FunctionCallbackInfo<v8::Value>&)’ to ‘v8::Isolate*’
../src/bindings.cc:25:85: error: no matching function for call to ‘v8::FunctionTemplate::New(void (&)(const v8::FunctionCallbackInfo<v8::Value>&))’
   Local<Function> listenerConstructor = FunctionTemplate::New(BusListenerConstructor)->GetFunction();
                                                                                     ^
../src/bindings.cc:25:85: note: candidate is:
In file included from /home/user/.node-gyp/0.12.2/src/node.h:61:0,
                 from ../src/bindings.cc:1:
/home/user/.node-gyp/0.12.2/deps/v8/include/v8.h:3455:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/user/.node-gyp/0.12.2/deps/v8/include/v8.h:3455:34: note:   no known conversion for argument 1 from ‘void(const v8::FunctionCallbackInfo<v8::Value>&)’ to ‘v8::Isolate*’
../src/bindings.cc:27:81: error: no matching function for call to ‘v8::FunctionTemplate::New(void (&)(const v8::FunctionCallbackInfo<v8::Value>&))’
   Local<Function> objectConstructor = FunctionTemplate::New(BusObjectConstructor)->GetFunction();
                                                                                 ^
../src/bindings.cc:27:81: note: candidate is:
In file included from /home/user/.node-gyp/0.12.2/src/node.h:61:0,
                 from ../src/bindings.cc:1:
/home/user/.node-gyp/0.12.2/deps/v8/include/v8.h:3455:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/user/.node-gyp/0.12.2/deps/v8/include/v8.h:3455:34: note:   no known conversion for argument 1 from ‘void(const v8::FunctionCallbackInfo<v8::Value>&)’ to ‘v8::Isolate*’
../src/bindings.cc:29:104: error: no matching function for call to ‘v8::FunctionTemplate::New(void (&)(const v8::FunctionCallbackInfo<v8::Value>&))’
   Local<Function> sessionPortListenerConstructor = FunctionTemplate::New(SessionPortListenerConstructor)->GetFunction();
                                                                                                        ^
../src/bindings.cc:29:104: note: candidate is:
In file included from /home/user/.node-gyp/0.12.2/src/node.h:61:0,
                 from ../src/bindings.cc:1:
/home/user/.node-gyp/0.12.2/deps/v8/include/v8.h:3455:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/user/.node-gyp/0.12.2/deps/v8/include/v8.h:3455:34: note:   no known conversion for argument 1 from ‘void(const v8::FunctionCallbackInfo<v8::Value>&)’ to ‘v8::Isolate*’
../src/bindings.cc:31:90: error: no matching function for call to ‘v8::FunctionTemplate::New(void (&)(const v8::FunctionCallbackInfo<v8::Value>&))’
   Local<Function> notificationConstructor = FunctionTemplate::New(NotificationConstructor)->GetFunction();
                                                                                          ^
../src/bindings.cc:31:90: note: candidate is:
In file included from /home/user/.node-gyp/0.12.2/src/node.h:61:0,
                 from ../src/bindings.cc:1:
/home/user/.node-gyp/0.12.2/deps/v8/include/v8.h:3455:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/user/.node-gyp/0.12.2/deps/v8/include/v8.h:3455:34: note:   no known conversion for argument 1 from ‘void(const v8::FunctionCallbackInfo<v8::Value>&)’ to ‘v8::Isolate*’
make: *** [Release/obj.target/node-alljoyn/src/bindings.o] Error 1
make: Leaving directory `/home/user/nodejs/node_modules/alljoyn/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.13.0-40-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/nodejs/node_modules/alljoyn
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "alljoyn"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! alljoyn@0.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alljoyn@0.1.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the alljoyn package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls alljoyn
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/nodejs/npm-debug.log

Can anyone help me to install alljoyn successfully.?

Thanks

**Comment by iamruinous** [comment]
We currently do not support node 0.12. IIRC version 0.10.35 is the best supported version of node for AllJoyn. We are currently working on a big improvement to this library and will be able to provide much better AllJoyn support.

**Comment by kgan4dev** [comment]
Thanks you.

**Comment by Injac** [comment]
Any news about this? I tried to install your alljoyn module today on a raspberry and it stops the installation with similar error messages. Why is a specific node version so important? Thanks :)

**Comment by kevwu** [comment]
I believe this is because the path for node has changed from /usr/bin/node to /usr/bin/nodejs.

If on a Debian-based system, try doing `sudo apt-get install nodejs-legacy`. Or you can just symlink /usr/bin/nodejs to /usr/bin/node. This worked for me.

**Comment by Injac** [comment]
Thanks for the feedback. I installed already node.js 0.10.35 which seems to have memory-leaking issues. But I am not sure about this. Everything runs fine, but somehow (running Express.js) as well, node is acquiring 1MB of RAM after each call. Within ours there seems not to be any kind of garbage collection. I am profiling my scripts tomorrow and will let you know about it. Remember, this has nothing to do with this package.

**Comment by kevwu** [comment]
Looks like the latest node version available on Ubuntu (at least the 14.04 LTS version I'm currently using) is 0.10.25. I'll try it with 0.12.x soon.

Also, in what may be a related issue, my node script is unable to find advertised names of other Alljoyn devices on the network, only other instances of itself running on the local machine. I've followed the examples to a T. Is there a chance this is because of the way this version of node handles networking?
