### ISSUE TITLE
npm install failed on Windows 10 Enterprise (node.js 0.12.7)

### ISSUE THREAD

**Issue by NNM11** [octoblu/alljoyn#15]
- Open the nodejs admin command prompt
- Run "npm install alljoyn"
- npm reported installation failure on node-gyp rebuild

-- log
C:\Windows\System32>npm install alljoyn
\
> alljoyn@1.0.0 install C:\Windows\System32\node_modules\alljoyn
> node-gyp rebuild

C:\Windows\System32\node_modules\alljoyn>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp: binding.gyp not found (cwd: C:\Windows\System32\node_modules\alljoyn) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Windows\System32\node_modules\alljoyn
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "alljoyn"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! alljoyn@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the alljoyn@1.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the alljoyn package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls alljoyn
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\System32\npm-debug.log

C:\Windows\System32>npm owner ls alljoyn
chrismatthieu <chris@matthieu.us>
phated <blaine@iceddev.com>
monteslu <monteslu@gmail.com>
octoblu <serveradmin@octoblu.com>

**Comment by RedCreepster** [comment]
+1

**Comment by rcoccia** [comment]
+1
