### ISSUE TITLE
npm install fails on OSX 10.10

### ISSUE THREAD

**Issue by chrylarson** [octoblu/alljoyn#8]
ran npm install alljoyn and received this error that says 'This is most likely a problem with alljoyn package, not npm itself. Tell the author that this fails on your system: node-gyp rebuild'

make: *** [Release/obj.target/node-alljoyn/src/BusConnection.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/chris/node_modules/alljoyn
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "alljoyn"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! alljoyn@0.1.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alljoyn@0.1.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the alljoyn package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls alljoyn
npm ERR! There is likely additional logging output above.

**Comment by plkumar** [comment]
+1 even i'm seeing the same issues.

**Comment by sisense** [comment]
Same error... 

warning generated.
  LIBTOOL-STATIC Release/liballjoyn.a
  CXX(target) Release/obj.target/allchat/src/test_allchat.o
  CXX(target) Release/obj.target/allchat/alljoyn/alljoyn_core/router/bundled/BundledRouter.o
  LINK(target) Release/allchat
  CXX(target) Release/obj.target/node-alljoyn/src/BusConnection.o
In file included from ../src/BusConnection.cc:1:
../../nan/nan.h:324:27: error: redefinition of 'NanEnsureHandleOrPersistent'
  NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                          ^
../../nan/nan.h:319:17: note: previous definition is here
  v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
                ^
../../nan/nan.h:344:27: error: redefinition of 'NanEnsureLocal'
  NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
                          ^
../../nan/nan.h:334:27: note: previous definition is here
  NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
                          ^
../../nan/nan.h:757:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../../nan/nan.h:768:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
