### ISSUE TITLE
npm install alljoyn failed in ubuntu 14.04.2

### ISSUE THREAD

**Issue by wongni** [octoblu/alljoyn#9]
I am getting the following errors during installing octoblu/alljoyn.

$ npm install alljoyn
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/nan
npm http 200 https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/bindings/-/bindings-1.2.1.tgz
npm http 200 https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/nan/-/nan-1.7.0.tgz
npm http 200 https://registry.npmjs.org/bindings/-/bindings-1.2.1.tgz
npm http 200 https://registry.npmjs.org/nan/-/nan-1.7.0.tgz

> alljoyn@0.1.4 install /home/sesa288124/octoblu/node_modules/alljoyn
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.16.0-30-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/sesa288124/octoblu/node_modules/alljoyn
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by iamruinous** [comment]
AllJoyn requires node v0.10.35 or higher in the 0.10 series. It does not work with 0.12 yet.

What version are you running?

**Comment by kevwu** [comment]
I was able to solve this:

I believe this is because the path for node has changed from /usr/bin/node to /usr/bin/nodejs.

If on a Debian-based system, try doing sudo apt-get install nodejs-legacy. Or you can just symlink /usr/bin/nodejs to /usr/bin/node. This worked for me.

**Comment by sapsaldog** [comment]
I did also solve this problem by using compiled nodejs & npm not packaged nodejs & npm
